### PR TITLE
Trim README.md and godoc

### PR DESCRIPTION
**Pull request by maruel**
- README.md: Put a link to godoc instead of copy-pasting documentation.
- README.md: Add note that it is tested to work on various micro-computer.
- Remove comment about physical memory size not changing, this is not strictly
  true, it is possible to add physical memory under certain circumstances.
- Add example both in godoc and in README.md

### CODE REVIEW

**Comment by maruel** [comment]
Thanks for the library, it's really cool. Here's some optional changes, as you see fit.

**Comment by pbnjay** [comment]
Hey Maruel - Thanks for the updates! I'd like to keep some of the notes on usage considerations so that people stumbling across this aren't completely in the dark. I know it won't be in the stdlib but some of the discussions there are good to know.

Do you know which arch those mini-computers are? ARM v7 and/or v8?

**Comment by maruel** [comment]
Added the link back, noted the arch of each machine, added an example that is copy-pastable in godoc and one simple in the README, here's how it looks: https://github.com/maruel/memory

**Comment by pbnjay** [comment]
LGTM! Thanks!

**Comment by maruel** [comment]
Ah dang I made a typo in the example, it should be %d, not %s.

**Pull request merged**
